#FROM openjdk:8-jdk-alpine
FROM szopen/openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=target/eap*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
