version: "3.8"

#name: eoa-system

services:

  server:
    image: openea-docker.pkg.coding.net/reps/docker/eoa-server:latest
    container_name: eoa-server
    restart: unless-stopped
    ports:
      - 48080:48080
    environment:
      # https://github.com/polovyivan/docker-pass-configs-to-container
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS:
        ${JAVA_OPTS:-
          -Xms512m
          -Xmx2049m
          -Djava.security.egd=file:/dev/./urandom
        }
      ARGS:
        --spring.datasource.dynamic.datasource.master.url=jdbc:mysql://10.0.4.13:3306/eoa-db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
        --spring.datasource.dynamic.datasource.master.username=eoa
        --spring.datasource.dynamic.datasource.master.password=${JDBC_PASSWORD:-eap}
        --spring.datasource.dynamic.datasource.slave.url=jdbc:mysql://10.0.4.13:3306/eoa-db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
        --spring.datasource.dynamic.datasource.slave.username=eoa
        --spring.datasource.dynamic.datasource.slave.password=${JDBC_PASSWORD:-eap}
        --spring.redis.host=10.0.4.4
        --spring.redis.port=6378
        --spring.redis.password=nopass
        --eap.enableOpenBpm=true
        --eap.userDataType=obpm
        --eap.obpm.apiBaseUrl=http://10.0.4.4:6330
    networks:
      - eoa-network

  web:
    image: openea-docker.pkg.coding.net/reps/docker/eoa-web:latest
    container_name: eoa-web
    restart: unless-stopped
    ports:
      - 7080:80
    networks:
      - eoa-network
    depends_on:
      - server

networks:
  eoa-network:
    driver: bridge
