package org.openea.eap.extj.model.visualJson;

import lombok.Data;
import org.openea.eap.extj.model.visualJson.config.ConfigModel;
import org.openea.eap.extj.model.visualJson.options.ColumnOptionModel;
import org.openea.eap.extj.model.visualJson.props.PropsModel;

import java.util.List;


@Data
public class FieLdsModel {
    private ConfigModel config;
    private SlotModel slot;
    private String placeholder;
    private Object style;
    private Boolean clearable;
    private String prefixicon;
    private Integer precision;
    private String suffixicon;
    private String maxlength;
    private Boolean showWordLimit;
    private Boolean readonly;
    private Boolean disabled;
    private String vModel = "";
    private String modelId = "";
    private Integer addType = 0;
    private String addTableConf;
    private String relationField;
    private Boolean relationChild = false;
    private String relationModel;
    private Boolean hasPage;
    private String pageSize;
    private String type;
    private Object autosize;
    private Integer step;
    private Boolean stepstrictly;
    private Object textStyle;
    private Integer lineHeight;
    private Integer fontSize;
    private Boolean showChinese;
    private Boolean showPassword;
    private String tipLabel;
    private String target;
    private String href;
    private String size;
    private Boolean filterable;
    private String showField;
    private Boolean multiple = false;
    private Boolean searchMultiple = false;
    private PropsModel props;
    private Boolean showAllLevels;
    private String separator;
    private Boolean isrange;
    private String rangeseparator;
    private String startplaceholder;
    private String endplaceholder;
    private String format;
    private String valueformat;
    private Object pickeroptions;
    private Integer max;
    private Boolean allowhalf;
    private Boolean showText;
    private Boolean showScore;
    private Boolean showAlpha;
    private String colorformat;
    private String activetext;
    private String inactivetext;
    private String activecolor;
    private String inactivecolor;
    private String activevalue;
    private String inactivevalue;
    private Integer min;
    private Boolean showStops;
    private Boolean range;
    private String content;
    private String header;
    private Boolean accordion;
    private String tabPosition;
    private String accept;
    private Boolean showTip;
    private Integer fileSize;
    private String sizeUnit;
    private Integer limit;
    private String contentposition;
    private String buttonText;
    private Integer level;
    private String options;
    private String actionText;
    private String shadow;
    private String name;
    private String title;
    private String pathType;
    private String isAccount;
    private String folder;
    private Integer searchType;
    private String interfaceId;
    private List<ColumnOptionModel> columnOptions;
    private String propsValue;
    private String activeTxt = "开";
    private String inactiveTxt = "关";
    private String lineColor;
    private String background;
    private Integer width;
    private Integer height;
    private String staticText;
    private String templateJson = "[]";
    private String dataType = "";
    private String colorDark;
    private String colorLight;
    private String align;
    private Boolean showSummary;
    private String summaryField;
    private String showLevel;
    private String popupType;
    private String popupTitle;
    private String popupWidth;
    private boolean closable;
    private boolean showIcon;
    private String selectType;
    private String ableDepIds;
    private String ablePosIds;
    private String ableUserIds;
    private String ableRoleIds;
    private String ableGroupIds;
    private String ableIds;
    private Integer childrenSize;
    private boolean needImport;
    private String relationTableForeign;
    private String mainTableId;
    private String childMainKey;
    private Integer tableType;
    private String beforeVmodel;
    private String description;
    private String closeText;
    private String tipText;
    private String direction;
    private String addonAfter;
    private String addonBefore;
    private Boolean isAmountChinese;
    private String controlsPosition;
    private String startTime;
    private String endTime;
    private String optionType;
    private Integer total;
    private boolean thousands = false;

}