server:
  port: ${port:8080}
  servlet:
    context-path: ${context-path:/}
    session:
      timeout: 1d
  shutdown: graceful #开启优雅停机

spring:
  application:
    name: OpenBpm
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 180s #设置缓冲时间 默认30s
  main:
    allow-circular-references: true  #fix兼容循环依赖
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #fix升级问题
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    type: ${ds_type:com.zaxxer.hikari.HikariDataSource}
    #mysql
    db-type: ${db_type:mysql}
    driver-class-name: ${jdbc_driver:com.mysql.cj.jdbc.Driver}
    url: ${jdbc_url:jdbc:mysql://mysql:3306/bpm-db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&nullCatalogMeansCurrent=true}
    username: ${jdbc_user:bpm}
    password: ${jdbc_password:bpm}

    hikari:
      pool-name: hikari-pool
      maximum-pool-size: ${mysql_pool_size:100}
      minimum-idle: 5
      idle-timeout: 180000
      connection-timeout: 30000
      max-lifetime: 3600000
      auto-commit: true
#      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
      connection-test-query: SELECT 1
  data:
    mongodb:
      uri: ${mongodb_url:}
  activemq:
    broker-url: ${activemq_url:tcp://activemq:61616}
    in-memory: false
    packages:
      trust-all: true
  redis:
    host: ${redis_host:redis}
    port: ${redis_port:6379}
    password: ${redis_password:}
    database: ${redis_database:0}
  cache:
    cache-names: cache1,cache2,dictNode,dictNode2,userById,dashboardTodoCount,currentMasterGroupIds,currentMasterGroupIds2
    redis:
      time-to-live: 600000
  liquibase:
    enabled: ${liquibase_enabled:false}
  freemarker:
    template-loader-path: classpath:/templates/
  servlet:
    multipart:
      max-file-size: ${max-file-size:1073741824} #1GB
      max-request-size: ${max-request-size:1073741824} #1GB
  #messages:
    #basename: i18n/messages,i18n/sys,i18n/org,i18n/bus,i18n/form,i18n/wf
    #encoding: UTF-8

#具体配置项可查看http://www.mybatis.org/mybatis-3/configuration.html#properties
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      column-format: "\"%s\""
  type-handlers-package: classpath*:org.openbpm.base.db.model.typehandler
  type-aliases-package: classpath*:**/dao
  mapper-locations: ["classpath*:/mapper/**/*.xml","classpath*:**/mapper","classpath*:**/mapping","classpath*:**/dao"]

logging:
  level:
    root: ${logging_level_root:INFO}
    org.openbpm: WARN
    org.openbpm.base.db: INFO
    org.openbpm.base.db.transaction: INFO
    org.springframework: WARN
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.data.redis: WARN
    org.springframework.jdbc.core.StatementCreatorUtils: WARN
    org.springframework.web.servlet.mvc.support: ERROR
    org.mybatis.spring.mapper.ClassPathMapperScanner: ERROR
    springfox.documentation.builders.FormParameterSpecificationProvider: ERROR
    springfox.documentation.swagger.readers.operation.OperationImplicitParameterReader: ERROR
  file:
    name: /app/logs/bpm-server.log

#security:
#  ignored:  [/openbpm-ui/**,/swagger-*,/v2/api-docs*,/doc.html,/css/**,/js/**,/images/**,/webjars/**,/**/favicon.ico]
## /swagger-*,/v2/api-docs*,   swagger 免登陆
bpm:
  cust:
    base-package: com.xxx.bpm
  jwt:
    enabled: ${jwt_enabled_:true}
  security:
    auth-ignores: ${security_auth_ignores:/login.*,/openbpm-ui*,/bpm-admin*,/bpm-mobile*,/index.html,/webjars/*,/swagger-*,/v2/api-docs*,/doc.html,/data/*,/Ashxs/*,/test/*,/common/email/*,/public/*,,/eap/login,/eap/userMenu}
    csrf-disable: true
    csrf-ignores: ${security_csrf_ignores:openbpm,127.0.0.1,localhost}
  mongoDb:
    db: ${mongodb_db:}
    col: ${mongodb_col:}
  simple-mq:
    message-queue-type: ${message_queue_type:synchronous}
  form:
    template:
      dirs: pc_vue, mobile

  bus-data:
    autofill:
      update-time: update_time_,lastdate
      update-by: update_by_,lastuid

  file:
    base-dir: ${file_base_dir:/app/data/files/}
    preview-base: ${preview_url_base:/fileview/}
    preview-password: ${preview_url_password:0000}
    uploader: ${file_uploader:ordinary}

eap:
  tenant: # 多租户相关配置项
    enable: false
  web:
    adminUi:
      url: http://dashboard.eap.openea.org # Admin 管理后台 UI 的地址

## 上传配置 db 存数据库 ，具体请看 IUploader 实现类
uploader:
  default: ordinary
  ordinary:
    path: ${ordinary_path:/app/data/files/}

